item { 
	name:'Piu'
	id:1
}
item { 
	name:'Meno'
	id:2
}
item { 
	name:'Conferma'
	id:3
}
item { 
	name:'Ruota'
	id:4
}
item { 
	name:'Saturazione'
	id:5
}
item { 
	name:'Luminosita'
	id:6
}
item { 
	name:'Contrasto'
	id:7
}
item { 
	name:'Visualizza'
	id:8
}
item { 
	name:'Filtri'
	id:9
}
item { 
	name:'Esci'
	id:10
}
